### ISSUE TITLE
 Umbrella issue to track "Conformane testing gateway-api implementations"

### ISSUE THREAD

**Issue by heyste** [apisnoop/gateway-api-test-framework#26]
### Gateway-API v1.0.0

| Task  | Cilium  | Contour | Envoy-Gateway | Istio |
| ------- | ------------- |  ------------- | ------------- | ------------- |
| kind cluster runs with default pods for implementation  | v1.15.4 |    |    |   | |
| Deployed gateway-provider for implementation  | n/a |   |    |   |
| GatewayClass has "status": "True" for  "type": "Accepted"  | True  |    |    |   |
| Apisnoop works with implementation | Yes |  |  |  |
| Completes conformance tests  | Yes |   |    |   |
| Generated report matches [past submissions](https://github.com/kubernetes-sigs/gateway-api/tree/main/conformance/reports/v1.0.0)  |    No |    |    |   |

**Comment by heyste** [comment]
Generate Conformance report for implementation: `cilium`

```
apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2024-06-05T15:37:36+12:00"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.0.0
implementation:
  contact:
  - https://github.com/cilium/community/blob/main/roles/Maintainers.md
  organization: cilium
  project: cilium
  url: https://github.com/cilium/cilium
  version: 0.15.4
kind: ConformanceReport
mode: default
profiles: null
```
