### ISSUE TITLE
Conformance report for Cilium doesn't match submission

### ISSUE THREAD

**Issue by heyste** [apisnoop/gateway-api-test-framework#34]
The generated report hasn't recorded any profile details.

```
apiVersion: gateway.networking.k8s.io/v1alpha1
date: "2024-06-05T15:37:36+12:00"
gatewayAPIChannel: experimental
gatewayAPIVersion: v1.0.0
implementation:
  contact:
  - https://github.com/cilium/community/blob/main/roles/Maintainers.md
  organization: cilium
  project: cilium
  url: https://github.com/cilium/cilium
  version: 0.15.4
kind: ConformanceReport
mode: default
profiles: null
```

Refer to v1.0.0 conformance submission: https://github.com/kubernetes-sigs/gateway-api/blob/main/conformance/reports/v1.0.0/cilium/v1.15.0-pre.3-report.yaml
